// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Project: tf-study-shelf-b1a08
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkMl7a5G3jTRSU06SL-QplpwQ62frCZUw',
    appId: '1:151064349456:android:861b5284f491fd684cf395',
    messagingSenderId: '151064349456',
    projectId: 'tf-study-shelf-b1a08',
    storageBucket: 'tf-study-shelf-b1a08.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkMl7a5G3jTRSU06SL-QplpwQ62frCZUw',
    appId: '1:151064349456:web:7b9ac82f1c3ca3124cf395',
    messagingSenderId: '151064349456',
    projectId: 'tf-study-shelf-b1a08',
    authDomain: 'tf-study-shelf-b1a08.firebaseapp.com',
    storageBucket: 'tf-study-shelf-b1a08.firebasestorage.app',
    measurementId: 'G-0SPKZNQMWE',
  );
}
